# Configurator
sw_configurator_edit:
    pattern:  /configurator/{configurationClass}/{namespace}
    defaults: { _controller: "SwDatabaseConfigBundle:Configurator:edit", namespace: '' }
    options: { do_not_remove: true }